title: shodan / junohm410
author: shodan
email: ""
description: > # this means to ignore newlines until "show_exerpts:"
  Studying Ruby, Rails | FjordBootCamp
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: shodan / junohm410
  tagline: "Studying Ruby, Rails | FjordBootCamp"
  date_format: "%b %-d, %Y"
  style: red
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: tonseishodan
    github: junohm410
    # linkedIn:
    rss: rss

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the pages in order as they should show up
  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
